name = "onchain-logger-frontend"
compatibility_date = "2024-11-28"
pages_build_output_dir = "dist"

[env.production]
name = "onchain-logger-frontend"

[env.preview]
name = "onchain-logger-frontend-preview"

